/**
 * PDF Export Service
 * Exports canvas mockups to PDF
 */

import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { store } from '../services/store.js';

export async function exportToPDF() {
    const mockup = store.getMockup();
    if (!mockup || !mockup.screens || mockup.screens.length === 0) {
        throw new Error('No mockup to export');
    }

    // Create PDF in landscape for better screen layout
    const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 15;

    // Add title page
    pdf.setFontSize(28);
    pdf.setTextColor(139, 92, 246); // Accent color
    pdf.text(mockup.appName || 'App Mockup', pageWidth / 2, 40, { align: 'center' });

    pdf.setFontSize(12);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Generated by AI Prototyper`, pageWidth / 2, 50, { align: 'center' });
    pdf.text(`${mockup.screens.length} screens`, pageWidth / 2, 58, { align: 'center' });
    pdf.text(new Date().toLocaleDateString(), pageWidth / 2, 66, { align: 'center' });

    // Add flow summary if exists
    if (mockup.flows && mockup.flows.length > 0) {
        pdf.setFontSize(14);
        pdf.setTextColor(60, 60, 60);
        pdf.text('User Flow', margin, 90);

        pdf.setFontSize(10);
        pdf.setTextColor(100, 100, 100);
        let flowY = 100;
        mockup.flows.forEach((flow, idx) => {
            pdf.text(`${idx + 1}. ${flow.from} → ${flow.to}${flow.label ? ` (${flow.label})` : ''}`, margin + 5, flowY);
            flowY += 8;
        });
    }

    // Capture each screen
    const screenWrappers = document.querySelectorAll('.screen-wrapper');

    for (let i = 0; i < screenWrappers.length; i++) {
        const screenWrapper = screenWrappers[i];
        const screen = mockup.screens[i];

        // Add new page for each screen
        pdf.addPage();

        // Screen title
        pdf.setFontSize(16);
        pdf.setTextColor(60, 60, 60);
        pdf.text(screen.name || `Screen ${i + 1}`, margin, 20);

        pdf.setFontSize(10);
        pdf.setTextColor(120, 120, 120);
        pdf.text(`Screen ${i + 1} of ${mockup.screens.length}`, pageWidth - margin, 20, { align: 'right' });

        try {
            // Capture screen as canvas
            const canvas = await html2canvas(screenWrapper, {
                backgroundColor: '#0a0a0f',
                scale: 2,
                logging: false,
                useCORS: true,
            });

            // Calculate dimensions to fit in page
            const imgWidth = 90; // mm
            const imgHeight = (canvas.height / canvas.width) * imgWidth;
            const xPos = (pageWidth - imgWidth) / 2;
            const yPos = 30;

            // Add image to PDF
            const imgData = canvas.toDataURL('image/png');
            pdf.addImage(imgData, 'PNG', xPos, yPos, imgWidth, Math.min(imgHeight, pageHeight - 50));

            // Add element list
            if (screen.elements && screen.elements.length > 0) {
                const listStartY = Math.min(yPos + imgHeight + 15, pageHeight - 60);

                pdf.setFontSize(12);
                pdf.setTextColor(80, 80, 80);
                pdf.text('Elements:', margin, listStartY);

                pdf.setFontSize(9);
                pdf.setTextColor(100, 100, 100);
                let elemY = listStartY + 8;

                screen.elements.slice(0, 10).forEach(elem => {
                    if (elemY > pageHeight - 20) return;
                    const text = elem.content?.text || elem.content?.title || elem.type;
                    pdf.text(`• ${elem.type}: ${text.substring(0, 50)}`, margin + 5, elemY);
                    elemY += 6;
                });

                if (screen.elements.length > 10) {
                    pdf.text(`... and ${screen.elements.length - 10} more elements`, margin + 5, elemY);
                }
            }
        } catch (err) {
            console.error('Error capturing screen:', err);
            pdf.setFontSize(12);
            pdf.setTextColor(200, 100, 100);
            pdf.text('Error capturing screen image', pageWidth / 2, 100, { align: 'center' });
        }
    }

    // Save PDF
    const filename = `${mockup.appName?.replace(/[^a-zA-Z0-9]/g, '_') || 'mockup'}_${Date.now()}.pdf`;
    pdf.save(filename);

    return filename;
}

export default exportToPDF;
